import { GameDetail, GameSummary } from './games.models';

export const MOCK_GAMES: GameDetail[] = [
  {
    id: 'g1',
    title: 'Super Metroid',
    system: 'SNES',
    region: 'NTSC-U',
    year: 1994,
    owned: true,
    favorite: true,
    hasArt: true,
    accent: '#2a6f7a',
    rating: 4.9,
    ratingCount: 1284,
    downloadCount: 412,
    releaseDate: '1994-03-19',
    description:
      'Explore planet Zebes as Samus Aran in this landmark action-adventure. Nonlinear exploration, atmospheric design, and precise combat defined a generation of Metroidvanias.',
    publisher: 'Nintendo',
    developer: 'Nintendo R&D1',
    genres: ['Action', 'Adventure'],
    tags: ['metroidvania', 'sci-fi', 'classic'],
    players: '1',
    languages: ['English', 'Japanese'],
    screenshots: ['#1a4a52', '#2a6f7a', '#3d8a96'],
    notes: 'CIB digital dump; verified good dump.',
    metadataSource: 'manual',
    externalId: '',
    screenshotCount: 3,
    playStatus: 'beaten',
    files: [
      { id: 'f1', name: 'Super Metroid (USA).sfc', sizeLabel: '3.0 MB', extension: '.sfc' },
      { id: 'f2', name: 'Super Metroid Manual.pdf', sizeLabel: '12 MB', extension: '.pdf' },
    ],
  },
  {
    id: 'g2',
    title: 'Sonic the Hedgehog 2',
    system: 'Genesis',
    region: 'NTSC-U',
    year: 1992,
    owned: true,
    favorite: false,
    hasArt: true,
    accent: '#1a5c9a',
    rating: 4.6,
    ratingCount: 902,
    downloadCount: 288,
    releaseDate: '1992-11-21',
    description: 'Classic 16-bit platformer introducing Tails and the spin dash, with co-op play and memorable zones.',
    publisher: 'Sega',
    developer: 'Sonic Team',
    genres: ['Platformer'],
    tags: ['mascot', 'co-op'],
    players: '1–2',
    languages: ['English'],
    screenshots: ['#0d3a6a', '#1a5c9a', '#2f7ab8'],
    notes: '',
    metadataSource: 'manual',
    externalId: '',
    screenshotCount: 3,
    playStatus: 'playing',
    files: [{ id: 'f3', name: 'Sonic the Hedgehog 2 (USA).md', sizeLabel: '1.0 MB', extension: '.md' }],
  },
  {
    id: 'g3',
    title: 'Castlevania: Symphony of the Night',
    system: 'PS1',
    region: 'NTSC-U',
    year: 1997,
    owned: true,
    favorite: true,
    hasArt: true,
    accent: '#52687a',
    rating: 4.8,
    ratingCount: 2103,
    downloadCount: 501,
    releaseDate: '1997-10-02',
    description: 'Genre-defining Metroidvania set in Dracula’s castle, blending RPG systems with gothic exploration.',
    publisher: 'Konami',
    developer: 'Konami',
    genres: ['Action', 'RPG'],
    tags: ['gothic', 'metroidvania'],
    players: '1',
    languages: ['English', 'Japanese'],
    screenshots: ['#3d4f5c', '#52687a', '#6a8094'],
    notes: 'Bin/cue pair.',
    metadataSource: 'manual',
    externalId: '',
    screenshotCount: 3,
    playStatus: 'beaten',
    files: [
      { id: 'f4', name: 'Castlevania - SOTN (USA).bin', sizeLabel: '650 MB', extension: '.bin' },
      { id: 'f5', name: 'Castlevania - SOTN (USA).cue', sizeLabel: '1 KB', extension: '.cue' },
    ],
  },
  {
    id: 'g4',
    title: 'The Legend of Zelda',
    system: 'NES',
    region: 'NTSC-U',
    year: 1986,
    owned: true,
    favorite: false,
    hasArt: false,
    accent: '#2a6f3a',
    rating: 4.7,
    ratingCount: 1560,
    downloadCount: 190,
    releaseDate: '1986-02-21',
    description: 'The original open-world adventure that established the Zelda formula of exploration, dungeons, and secrets.',
    publisher: 'Nintendo',
    developer: 'Nintendo',
    genres: ['Adventure'],
    tags: ['open-world', 'classic'],
    players: '1',
    languages: ['English', 'Japanese'],
    screenshots: ['#1a4a28', '#2a6f3a'],
    notes: 'Needs cover art.',
    metadataSource: 'manual',
    externalId: '',
    screenshotCount: 2,
    playStatus: 'unplayed',
    files: [{ id: 'f6', name: 'Legend of Zelda, The (USA).nes', sizeLabel: '128 KB', extension: '.nes' }],
  },
  {
    id: 'g5',
    title: 'Streets of Rage 2',
    system: 'Genesis',
    region: 'NTSC-U',
    year: 1992,
    owned: true,
    favorite: false,
    hasArt: true,
    accent: '#8a3a2a',
    rating: 4.5,
    ratingCount: 744,
    downloadCount: 156,
    releaseDate: '1992-12-20',
    description: 'Beat-em-up classic with Yuzo Koshiro’s iconic soundtrack and deep combat for its era.',
    publisher: 'Sega',
    developer: 'Sega',
    genres: ['Beat em up'],
    tags: ['co-op', 'arcade'],
    players: '1–2',
    languages: ['English'],
    screenshots: ['#5a2018', '#8a3a2a', '#aa4a3a'],
    notes: '',
    metadataSource: 'manual',
    externalId: '',
    screenshotCount: 3,
    playStatus: 'unplayed',
    files: [{ id: 'f7', name: 'Streets of Rage 2 (USA).md', sizeLabel: '2.0 MB', extension: '.md' }],
  },
  {
    id: 'g6',
    title: 'Final Fantasy VII',
    system: 'PS1',
    region: 'NTSC-U',
    year: 1997,
    owned: false,
    favorite: true,
    hasArt: true,
    accent: '#3a4a8a',
    rating: 4.8,
    ratingCount: 3401,
    downloadCount: 0,
    releaseDate: '1997-09-07',
    description: 'Landmark JRPG following Cloud Strife and companions against Shinra and Sephiroth.',
    publisher: 'Square',
    developer: 'Square',
    genres: ['RPG'],
    tags: ['jrpg', 'wishlist'],
    players: '1',
    languages: ['English', 'Japanese'],
    screenshots: ['#2a345a', '#3a4a8a', '#5a6aaa'],
    notes: 'Wishlist entry — track physical CIB separately.',
    metadataSource: 'manual',
    externalId: '',
    screenshotCount: 3,
    playStatus: 'wishlist',
    files: [],
  },
  {
    id: 'g7',
    title: 'Kirby’s Adventure',
    system: 'NES',
    region: 'NTSC-U',
    year: 1993,
    owned: true,
    favorite: false,
    hasArt: true,
    accent: '#8a4a7a',
    rating: 4.4,
    ratingCount: 512,
    downloadCount: 98,
    releaseDate: '1993-05-01',
    description: 'Colorful platformer introducing Copy Abilities on the NES.',
    publisher: 'Nintendo',
    developer: 'HAL Laboratory',
    genres: ['Platformer'],
    tags: ['family', 'abilities'],
    players: '1',
    languages: ['English'],
    screenshots: ['#6a2a5a', '#8a4a7a'],
    notes: '',
    metadataSource: 'manual',
    externalId: '',
    screenshotCount: 2,
    playStatus: 'beaten',
    files: [{ id: 'f8', name: "Kirby's Adventure (USA).nes", sizeLabel: '512 KB', extension: '.nes' }],
  },
  {
    id: 'g8',
    title: 'Chrono Trigger',
    system: 'SNES',
    region: 'NTSC-U',
    year: 1995,
    owned: true,
    favorite: true,
    hasArt: true,
    accent: '#4a6a2a',
    rating: 4.95,
    ratingCount: 2890,
    downloadCount: 377,
    releaseDate: '1995-03-11',
    description: 'Time-traveling RPG masterpiece with multiple endings and an all-star development team.',
    publisher: 'Square',
    developer: 'Square',
    genres: ['RPG'],
    tags: ['time-travel', 'classic'],
    players: '1',
    languages: ['English', 'Japanese'],
    screenshots: ['#2a4a18', '#4a6a2a', '#6a8a3a'],
    notes: '',
    metadataSource: 'manual',
    externalId: '',
    screenshotCount: 3,
    playStatus: 'playing',
    files: [{ id: 'f9', name: 'Chrono Trigger (USA).sfc', sizeLabel: '4.0 MB', extension: '.sfc' }],
  },
];

/** Per-user favorite / play overlays keyed by userId → gameId */
export const MOCK_USER_GAME_STATE: Record<string, Record<string, { favorite: boolean; playStatus: GameDetail['playStatus'] }>> = {
  u1: {
    g1: { favorite: true, playStatus: 'beaten' },
    g2: { favorite: false, playStatus: 'playing' },
    g3: { favorite: true, playStatus: 'beaten' },
    g6: { favorite: true, playStatus: 'wishlist' },
    g8: { favorite: true, playStatus: 'playing' },
  },
  u2: {
    g1: { favorite: true, playStatus: 'playing' },
    g5: { favorite: true, playStatus: 'beaten' },
  },
  u3: {
    g7: { favorite: true, playStatus: 'beaten' },
  },
};

export function toSummary(game: GameDetail): GameSummary {
  return {
    id: game.id,
    title: game.title,
    system: game.system,
    region: game.region,
    year: game.year,
    owned: game.owned,
    hasArt: game.hasArt,
    accent: game.accent,
    rating: game.rating,
    downloadCount: game.downloadCount,
    publisher: game.publisher,
    genres: game.genres,
  };
}
