import { PhysicalItem } from './physical.models';

export const MOCK_PHYSICAL: PhysicalItem[] = [
  {
    id: 'p1',
    title: 'Super Mario Bros. 3',
    system: 'NES',
    condition: 'good',
    locationId: 'loc1',
    locationName: 'Shelf A1',
    completeness: 'cib',
    checkedOut: false,
    accent: '#c43c3c',
  },
  {
    id: 'p2',
    title: 'Pokemon Red',
    system: 'Game Boy',
    condition: 'fair',
    locationId: 'loc3',
    locationName: 'Bin B2',
    completeness: 'cart',
    checkedOut: true,
    borrower: 'Alex',
    accent: '#c45c3c',
  },
  {
    id: 'p3',
    title: 'EarthBound',
    system: 'SNES',
    condition: 'mint',
    locationId: 'loc2',
    locationName: 'Shelf A2',
    completeness: 'cib',
    checkedOut: false,
    accent: '#3c8c4c',
  },
  {
    id: 'p4',
    title: 'Sega Genesis Model 1',
    system: 'Hardware',
    condition: 'good',
    locationId: 'loc4',
    locationName: 'Cabinet 1',
    completeness: 'box',
    checkedOut: false,
    accent: '#3c5cac',
  },
  {
    id: 'p5',
    title: 'Chrono Trigger',
    system: 'SNES',
    condition: 'good',
    locationId: 'loc2',
    locationName: 'Shelf A2',
    completeness: 'cib',
    checkedOut: false,
    accent: '#4a6a2a',
  },
  {
    id: 'p6',
    title: 'GameCube Controller',
    system: 'Hardware',
    condition: 'fair',
    locationId: 'loc5',
    locationName: 'Bin C1',
    completeness: 'loose',
    checkedOut: false,
    accent: '#6a4cac',
  },
];
