import { PhysicalItem } from './physical.models';

export const MOCK_PHYSICAL: PhysicalItem[] = [
  {
    id: 'p1',
    gameId: 'g1',
    title: 'Super Mario Bros. 3',
    system: 'NES',
    condition: 'good',
    locationId: 'loc1',
    locationName: 'Shelf A1',
    completeness: 'cib',
    checkedOut: false,
    accent: '#c43c3c',
    hasArt: false,
    year: 1990,
  },
  {
    id: 'p2',
    gameId: 'g2',
    title: 'Pokemon Red',
    system: 'Game Boy',
    condition: 'fair',
    locationId: 'loc3',
    locationName: 'Bin B2',
    completeness: 'cart',
    checkedOut: true,
    borrower: 'Alex',
    accent: '#c45c3c',
    hasArt: false,
    year: 1996,
  },
  {
    id: 'p3',
    gameId: 'g3',
    title: 'EarthBound',
    system: 'SNES',
    condition: 'mint',
    locationId: 'loc2',
    locationName: 'Shelf A2',
    completeness: 'cib',
    checkedOut: false,
    accent: '#3c8c4c',
    hasArt: false,
    year: 1995,
  },
];
