import { GameSystem } from './systems.models';

export const MOCK_SYSTEMS: GameSystem[] = [
  {
    id: 's1',
    name: 'Nintendo Entertainment System',
    shortName: 'NES',
    manufacturer: 'Nintendo',
    extensions: ['.nes', '.unf', '.fds'],
    gameCount: 42,
    icon: 'sports_esports',
    accent: '#c43c3c',
  },
  {
    id: 's2',
    name: 'Super Nintendo',
    shortName: 'SNES',
    manufacturer: 'Nintendo',
    extensions: ['.sfc', '.smc'],
    gameCount: 58,
    icon: 'stadia_controller',
    accent: '#5a6aac',
  },
  {
    id: 's3',
    name: 'Sega Genesis',
    shortName: 'Genesis',
    manufacturer: 'Sega',
    extensions: ['.md', '.gen', '.bin'],
    gameCount: 36,
    icon: 'videogame_asset',
    accent: '#1a5c9a',
  },
  {
    id: 's4',
    name: 'PlayStation',
    shortName: 'PS1',
    manufacturer: 'Sony',
    extensions: ['.bin', '.cue', '.chd', '.pbp'],
    gameCount: 29,
    icon: 'album',
    accent: '#3a4a8a',
  },
  {
    id: 's5',
    name: 'Game Boy',
    shortName: 'GB',
    manufacturer: 'Nintendo',
    extensions: ['.gb', '.gbc'],
    gameCount: 21,
    icon: 'smartphone',
    accent: '#6a8a3a',
  },
];
