import { GameSystem } from './systems.models';

export const MOCK_SYSTEMS: GameSystem[] = [
  {
    id: 's1',
    name: 'Nintendo Entertainment System',
    shortName: 'NES',
    manufacturer: 'Nintendo',
    extensions: ['.nes', '.unf', '.fds'],
    gameCount: 42,
    icon: 'sports_esports',
    accent: '#c43c3c',
    description: '8-bit home console that defined a generation of games.',
    releasePeriod: '1983–2003',
    generation: '8-bit',
    region: 'Worldwide',
    hasLogo: false,
    preferredStoragePath: '',
    metadataProviderIds: { libretro: 'Nintendo - Nintendo Entertainment System' },
    emulatorInfo: '',
    emulatorJsCore: 'nes',
    status: 'active',
  },
  {
    id: 's2',
    name: 'Super Nintendo',
    shortName: 'SNES',
    manufacturer: 'Nintendo',
    extensions: ['.sfc', '.smc'],
    gameCount: 58,
    icon: 'stadia_controller',
    accent: '#5a6aac',
    description: '16-bit console with Mode 7 graphics and a landmark library.',
    releasePeriod: '1990–2003',
    generation: '16-bit',
    region: 'Worldwide',
    hasLogo: false,
    preferredStoragePath: '',
    metadataProviderIds: { libretro: 'Nintendo - Super Nintendo Entertainment System' },
    emulatorInfo: '',
    emulatorJsCore: 'snes',
    status: 'active',
  },
  {
    id: 's3',
    name: 'Sega Genesis',
    shortName: 'Genesis',
    manufacturer: 'Sega',
    extensions: ['.md', '.gen', '.bin'],
    gameCount: 36,
    icon: 'videogame_asset',
    accent: '#1a5c9a',
    description: 'Sega’s 16-bit console, known as Mega Drive outside North America.',
    releasePeriod: '1988–1997',
    generation: '16-bit',
    region: 'Worldwide',
    hasLogo: false,
    preferredStoragePath: '',
    metadataProviderIds: { libretro: 'Sega - Mega Drive - Genesis' },
    emulatorInfo: '',
    emulatorJsCore: 'segaMD',
    status: 'active',
  },
  {
    id: 's4',
    name: 'PlayStation',
    shortName: 'PS1',
    manufacturer: 'Sony',
    extensions: ['.bin', '.cue', '.chd', '.pbp'],
    gameCount: 29,
    icon: 'album',
    accent: '#3a4a8a',
    description: 'Sony’s first home console and the CD-based 32-bit era.',
    releasePeriod: '1994–2006',
    generation: '32-bit',
    region: 'Worldwide',
    hasLogo: false,
    preferredStoragePath: '',
    metadataProviderIds: { libretro: 'Sony - PlayStation' },
    emulatorInfo: '',
    emulatorJsCore: '',
    status: 'active',
  },
  {
    id: 's5',
    name: 'Game Boy',
    shortName: 'GB',
    manufacturer: 'Nintendo',
    extensions: ['.gb', '.gbc'],
    gameCount: 21,
    icon: 'smartphone',
    accent: '#6a8a3a',
    description: 'Portable 8-bit handheld with a massive cartridge library.',
    releasePeriod: '1989–2003',
    generation: '8-bit',
    region: 'Worldwide',
    hasLogo: false,
    preferredStoragePath: '',
    metadataProviderIds: { libretro: 'Nintendo - Game Boy' },
    emulatorInfo: '',
    emulatorJsCore: 'gb',
    status: 'active',
  },
];
